from Pin import Pin

pin = Pin("name", "description", "author_id", "latitude", "longitude")
print(pin.id)
pin.name = ("hola", "idk")
print(pin.name)
pin.name = ("bola", "author_id")
print(pin.name)
print(pin.description)
pin.description = ("bola", "autr_id")
print(pin.description)
pin.description = ("bola", "author_id")
print(pin.name)
print(pin.author_id)
print(pin.coordinates)
pin.coordinates = ("hola", "bola", "hol")
print(pin.coordinates)
pin.coordinates = ("hola", "bola", "author_id")
print(pin.coordinates)
print(pin.attributes)
print(pin['RedFlag'])
print(pin['RedFlag'].__bool__())
print(pin['RedFlag'].add_review(True).add_review(False).add_review(False))
print(pin['RedFlag'].__bool__())